// <auto-generated />
using System;
using Incidents.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Incidents.Infrastructure.Migrations
{
    [DbContext(typeof(IncidentsDbContext))]
    [Migration("20230920070015_ChengedSeedAddedForeignKeysScenaryIdThreatId")]
    partial class ChengedSeedAddedForeignKeysScenaryIdThreatId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Incidents.Domain.Entities.Ambit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("Name");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Name"));

                    b.ToTable("Ambits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Software"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Functionality"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phase"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Release"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Service"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Transmission Channels"
                        },
                        new
                        {
                            Id = 7,
                            Name = "CICS"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Database"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hardware Host"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Hardware Open"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Middleware"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Networks"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Security"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Basic Host Software"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Open Basic Software"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Service Software"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Storage"
                        });
                });

            modelBuilder.Entity("Incidents.Domain.Entities.AmbitsToTypes", b =>
                {
                    b.Property<int>("AmbitId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("AmbitId", "TypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("AmbitsToTypes");

                    b.HasData(
                        new
                        {
                            AmbitId = 3,
                            TypeId = 1
                        },
                        new
                        {
                            AmbitId = 3,
                            TypeId = 2
                        },
                        new
                        {
                            AmbitId = 2,
                            TypeId = 2
                        },
                        new
                        {
                            AmbitId = 2,
                            TypeId = 3
                        },
                        new
                        {
                            AmbitId = 4,
                            TypeId = 4
                        },
                        new
                        {
                            AmbitId = 1,
                            TypeId = 4
                        },
                        new
                        {
                            AmbitId = 1,
                            TypeId = 5
                        },
                        new
                        {
                            AmbitId = 1,
                            TypeId = 1
                        },
                        new
                        {
                            AmbitId = 1,
                            TypeId = 6
                        },
                        new
                        {
                            AmbitId = 1,
                            TypeId = 3
                        },
                        new
                        {
                            AmbitId = 1,
                            TypeId = 7
                        },
                        new
                        {
                            AmbitId = 5,
                            TypeId = 3
                        },
                        new
                        {
                            AmbitId = 6,
                            TypeId = 2
                        },
                        new
                        {
                            AmbitId = 6,
                            TypeId = 7
                        },
                        new
                        {
                            AmbitId = 6,
                            TypeId = 1
                        },
                        new
                        {
                            AmbitId = 7,
                            TypeId = 8
                        },
                        new
                        {
                            AmbitId = 7,
                            TypeId = 1
                        },
                        new
                        {
                            AmbitId = 8,
                            TypeId = 9
                        },
                        new
                        {
                            AmbitId = 8,
                            TypeId = 8
                        },
                        new
                        {
                            AmbitId = 8,
                            TypeId = 2
                        },
                        new
                        {
                            AmbitId = 8,
                            TypeId = 7
                        },
                        new
                        {
                            AmbitId = 9,
                            TypeId = 7
                        },
                        new
                        {
                            AmbitId = 9,
                            TypeId = 6
                        },
                        new
                        {
                            AmbitId = 10,
                            TypeId = 4
                        },
                        new
                        {
                            AmbitId = 10,
                            TypeId = 10
                        },
                        new
                        {
                            AmbitId = 10,
                            TypeId = 9
                        },
                        new
                        {
                            AmbitId = 10,
                            TypeId = 7
                        },
                        new
                        {
                            AmbitId = 11,
                            TypeId = 4
                        },
                        new
                        {
                            AmbitId = 11,
                            TypeId = 2
                        },
                        new
                        {
                            AmbitId = 11,
                            TypeId = 7
                        },
                        new
                        {
                            AmbitId = 11,
                            TypeId = 6
                        },
                        new
                        {
                            AmbitId = 12,
                            TypeId = 4
                        },
                        new
                        {
                            AmbitId = 13,
                            TypeId = 11
                        },
                        new
                        {
                            AmbitId = 13,
                            TypeId = 12
                        },
                        new
                        {
                            AmbitId = 13,
                            TypeId = 13
                        },
                        new
                        {
                            AmbitId = 13,
                            TypeId = 1
                        },
                        new
                        {
                            AmbitId = 13,
                            TypeId = 14
                        },
                        new
                        {
                            AmbitId = 13,
                            TypeId = 15
                        },
                        new
                        {
                            AmbitId = 13,
                            TypeId = 16
                        },
                        new
                        {
                            AmbitId = 14,
                            TypeId = 7
                        },
                        new
                        {
                            AmbitId = 15,
                            TypeId = 7
                        },
                        new
                        {
                            AmbitId = 15,
                            TypeId = 6
                        },
                        new
                        {
                            AmbitId = 16,
                            TypeId = 10
                        },
                        new
                        {
                            AmbitId = 16,
                            TypeId = 9
                        },
                        new
                        {
                            AmbitId = 16,
                            TypeId = 6
                        },
                        new
                        {
                            AmbitId = 17,
                            TypeId = 6
                        });
                });

            modelBuilder.Entity("Incidents.Domain.Entities.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AmbitId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("ApplicationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("IncidentTypeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OriginId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("ProblemSummery")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RequestNr")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<int>("ScenaryId")
                        .HasColumnType("int");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("SubCause")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subsystem")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ThirdParty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ThreatId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AmbitId");

                    b.HasIndex("IncidentTypeId");

                    b.HasIndex("OriginId");

                    b.HasIndex("RequestNr")
                        .IsUnique();

                    b.HasIndex("ScenaryId");

                    b.HasIndex("ThreatId");

                    b.ToTable("Incidents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmbitId = 3,
                            ApplicationType = "Application Type",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 0,
                            IncidentTypeId = 1,
                            OpenDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OriginId = 1,
                            ProblemDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            ProblemSummery = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            RequestNr = "host0000007415837",
                            ScenaryId = 1,
                            Solution = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            SubCause = "definition change",
                            Subsystem = "cr",
                            ThirdParty = "AAA1",
                            ThreatId = 1,
                            Type = "Request Intervention",
                            Urgency = "Hight"
                        });
                });

            modelBuilder.Entity("Incidents.Domain.Entities.IncidentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("Name");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Name"));

                    b.ToTable("IncidentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Configuration"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Software Malfunction"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Third Parts"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Incorrect Change"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Code"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Resource Saturation"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Insufficient Resources"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Hardware Malfunction"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Degradation"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Block"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Accesses"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Cyber Attacks"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Certificates"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Firewall"
                        },
                        new
                        {
                            Id = 15,
                            Name = "IDM"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Patching"
                        });
                });

            modelBuilder.Entity("Incidents.Domain.Entities.Origin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Origins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Application"
                        },
                        new
                        {
                            Id = 2,
                            Name = "External"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Infrastructure"
                        });
                });

            modelBuilder.Entity("Incidents.Domain.Entities.OriginsToAmbit", b =>
                {
                    b.Property<int>("OriginId")
                        .HasColumnType("int");

                    b.Property<int>("AmbitId")
                        .HasColumnType("int");

                    b.HasKey("OriginId", "AmbitId");

                    b.HasIndex("AmbitId");

                    b.ToTable("OriginsToAmbit");

                    b.HasData(
                        new
                        {
                            OriginId = 1,
                            AmbitId = 3
                        },
                        new
                        {
                            OriginId = 1,
                            AmbitId = 2
                        },
                        new
                        {
                            OriginId = 1,
                            AmbitId = 4
                        },
                        new
                        {
                            OriginId = 1,
                            AmbitId = 1
                        },
                        new
                        {
                            OriginId = 2,
                            AmbitId = 2
                        },
                        new
                        {
                            OriginId = 2,
                            AmbitId = 5
                        },
                        new
                        {
                            OriginId = 2,
                            AmbitId = 1
                        },
                        new
                        {
                            OriginId = 3,
                            AmbitId = 6
                        },
                        new
                        {
                            OriginId = 3,
                            AmbitId = 7
                        },
                        new
                        {
                            OriginId = 3,
                            AmbitId = 8
                        },
                        new
                        {
                            OriginId = 3,
                            AmbitId = 3
                        },
                        new
                        {
                            OriginId = 3,
                            AmbitId = 9
                        },
                        new
                        {
                            OriginId = 3,
                            AmbitId = 10
                        },
                        new
                        {
                            OriginId = 3,
                            AmbitId = 11
                        },
                        new
                        {
                            OriginId = 3,
                            AmbitId = 12
                        },
                        new
                        {
                            OriginId = 3,
                            AmbitId = 13
                        },
                        new
                        {
                            OriginId = 3,
                            AmbitId = 1
                        },
                        new
                        {
                            OriginId = 3,
                            AmbitId = 14
                        },
                        new
                        {
                            OriginId = 3,
                            AmbitId = 15
                        },
                        new
                        {
                            OriginId = 3,
                            AmbitId = 16
                        },
                        new
                        {
                            OriginId = 3,
                            AmbitId = 17
                        });
                });

            modelBuilder.Entity("Incidents.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("Name")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Name"));

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "User that can add, modify and disable other users, change data manually.",
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Description = "User that can import data from a CSV file.",
                            Name = "Operator"
                        },
                        new
                        {
                            Id = 3,
                            Description = "User that can can view information about incidents.",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Incidents.Domain.Entities.Scenary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "A2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "A3"
                        });
                });

            modelBuilder.Entity("Incidents.Domain.Entities.Threat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Threats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AA1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AA2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AA3"
                        });
                });

            modelBuilder.Entity("Incidents.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = 0,
                            Email = "admin@mail.com",
                            FullName = "Admin",
                            IsEnabled = true,
                            Password = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
                            UserName = "cr00001"
                        });
                });

            modelBuilder.Entity("Incidents.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Incidents.Domain.Entities.AmbitsToTypes", b =>
                {
                    b.HasOne("Incidents.Domain.Entities.Ambit", "IncidentAmbit")
                        .WithMany("AmbitsToTypes")
                        .HasForeignKey("AmbitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Incidents.Domain.Entities.IncidentType", "IncidentType")
                        .WithMany("AmbitsToTypes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("IncidentAmbit");

                    b.Navigation("IncidentType");
                });

            modelBuilder.Entity("Incidents.Domain.Entities.Incident", b =>
                {
                    b.HasOne("Incidents.Domain.Entities.Ambit", "Ambit")
                        .WithMany("Incidents")
                        .HasForeignKey("AmbitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Incidents.Domain.Entities.IncidentType", "IncidentType")
                        .WithMany("Incidents")
                        .HasForeignKey("IncidentTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Incidents.Domain.Entities.Origin", "Origin")
                        .WithMany("Incidents")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Incidents.Domain.Entities.Scenary", "Scenary")
                        .WithMany("Incidents")
                        .HasForeignKey("ScenaryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Incidents.Domain.Entities.Threat", "Threat")
                        .WithMany("Incidents")
                        .HasForeignKey("ThreatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ambit");

                    b.Navigation("IncidentType");

                    b.Navigation("Origin");

                    b.Navigation("Scenary");

                    b.Navigation("Threat");
                });

            modelBuilder.Entity("Incidents.Domain.Entities.OriginsToAmbit", b =>
                {
                    b.HasOne("Incidents.Domain.Entities.Ambit", "Ambit")
                        .WithMany("OriginsToAmbits")
                        .HasForeignKey("AmbitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Incidents.Domain.Entities.Origin", "Origin")
                        .WithMany("OriginsToAmbits")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ambit");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("Incidents.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Incidents.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Incidents.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Incidents.Domain.Entities.Ambit", b =>
                {
                    b.Navigation("AmbitsToTypes");

                    b.Navigation("Incidents");

                    b.Navigation("OriginsToAmbits");
                });

            modelBuilder.Entity("Incidents.Domain.Entities.IncidentType", b =>
                {
                    b.Navigation("AmbitsToTypes");

                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("Incidents.Domain.Entities.Origin", b =>
                {
                    b.Navigation("Incidents");

                    b.Navigation("OriginsToAmbits");
                });

            modelBuilder.Entity("Incidents.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Incidents.Domain.Entities.Scenary", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("Incidents.Domain.Entities.Threat", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("Incidents.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
